import "./Insights.css";
import { Brain, TriangleAlert, TrendingUp, Lightbulb } from "lucide-react";

export default function Insights({ data }) {
  if (!data) return null;

  const insights = [];

  // Add executive summary as first insight
  if (data.executive_summary) {
    insights.push({
      icon: <Brain size={20} />,
      title: "Executive Summary",
      description: data.executive_summary,
      type: "info"
    });
  }

  // Add business impact
  if (data.business_impact) {
    insights.push({
      icon: <TrendingUp size={20} />,
      title: "Business Impact",
      description: data.business_impact,
      type: "success"
    });
  }

  // Add recommended action
  if (data.recommended_action) {
    insights.push({
      icon: <Lightbulb size={20} />,
      title: "Recommended Action",
      description: data.recommended_action,
      type: "warning"
    });
  }

  // Add top recommendation from engine
  if (data.recommendations && data.recommendations.length > 0) {
    const topRec = data.recommendations[0];
    insights.push({
      icon: <TriangleAlert size={20} />,
      title: `Risk: ${topRec.priority} Priority`,
      description: topRec.recommendation,
      type: topRec.priority === "Critical" || topRec.priority === "High" ? "critical" : "warning"
    });
  }

  return (
    <div className="dashboard-card">
      <div className="insight-header">
        <div>
          <h3 className="card-title">AI Executive Insights</h3>
          <p>Intelligent recommendations generated by RegMap AI</p>
        </div>
      </div>
      <div className="insight-list">
        {insights.map((item, index) => (
          <div className={`insight-item ${item.type}`} key={index}>
            <div className="insight-icon">{item.icon}</div>
            <div className="insight-content">
              <h4>{item.title}</h4>
              <p>{item.description}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}